### ISSUE TITLE
Better downloading workflow for resource tight systems

### ISSUE THREAD

**Issue by mainnet-pat** [dogechain-lab/dogechain-snapshots#2]
Hello, for avoiding multistep process of data downloading and unpacking one can achieve the same with the following command:
```bash
wget http://snapshots.dogechain.dog/dogechain.2022-12-01T03_14_43-UTC.snapshot.zst -O - | zstd -d -c - | tar -xvf - -C ./
```

This avoids creation of transient filesystem artifacts and unpacks everything in-place.

**Comment by DarianShawn** [comment]
Wow, thanks for the brilliant answer.
If the network is fast and stable enough, pipe them all together do make it more smooth.
But we have to consider more edge case, so we split the process.

Anyway, we will add your advice into the doc.

**Comment by 0xcb9ff9** [comment]
Ok, add it
